---
abstract: 'suite for make books and docs in pod6 format'
author:
  - 'Zahatski Aliaksandr zag@cpan.org'
build_requires: {}
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WriteAt
provides:
  WriteAt:
    file: lib/WriteAt.pm
    version: 0.02
  WriteAt::AUTHOR:
    file: lib/WriteAt/AUTHOR.pm
    version: 0
  WriteAt::CHANGES:
    file: lib/WriteAt/CHANGES.pm
    version: 0
  WriteAt::To:
    file: lib/WriteAt/To.pm
    version: 0
  WriteAt::To::DocBook:
    file: lib/WriteAt/To/DocBook.pm
    version: 0
requires:
  Perl6::Pod: 0.55
  Perl6::Pod::Lib: 0.11
  Regexp::Grammars: 1.015
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=WriteAt
  license: http://dev.perl.org/licenses/
  repository: git://github.com/zag/writeat.git
version: 0.02
