---
abstract: 'suite for make books and docs in pod6 format'
author:
  - 'Zahatski Aliaksandr zag@cpan.org'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WriteAt
provides:
  WriteAt:
    file: lib/WriteAt.pm
    version: 0.05
  WriteAt::AUTHOR:
    file: lib/WriteAt/AUTHOR.pm
    version: 0
  WriteAt::CHANGES:
    file: lib/WriteAt/CHANGES.pm
    version: 0
  WriteAt::To:
    file: lib/WriteAt/To.pm
    version: 0
  WriteAt::To::Atom:
    file: lib/WriteAt/To/Atom.pm
    version: 0
  WriteAt::To::DocBook:
    file: lib/WriteAt/To/DocBook.pm
    version: 0
  WriteAt::To::Latex:
    file: lib/WriteAt/To/Latex.pm
    version: 0
  WriteAt::UtilCTX:
    file: lib/WriteAt.pm
    version: 0
requires:
  DateTime::Format::W3CDTF: 0
  Perl6::Pod: 0.57
  Perl6::Pod::Lib: 0.12
  Regexp::Grammars: 1.021
  Template: 2.24
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=WriteAt
  license: http://dev.perl.org/licenses/
  repository: git://github.com/zag/writeat.git
version: 0.05
